language: php

sudo: false

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: PHPLINT=1 PHPCS=1
    - php: 7.0
      env: PHPLINT=1
    - php: 5.6
      env: PHPLINT=1

cache:
  directories:
    - vendor

before_install:
- phpenv config-rm xdebug.ini || echo 'No xdebug config.'


install:
- if [[ "$PHPCS" != "1" ]]; then composer install --no-dev --no-interaction; fi
- if [[ "$PHPCS" == "1" ]]; then composer install --no-interaction; fi

script:
- if [[ "$PHPLINT" == "1" ]]; then find -L .  -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l; fi
- if [[ "$PHPCS" == "1" ]]; then vendor/bin/phpcs -v; fi
