language: php

sudo: false

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: PHPLINT=1
    - php: 7.0
      env: PHPLINT=1
    - php: 5.6
      env: PHPLINT=1

cache:
  directories:
    - vendor

install:
- composer install --no-interaction

script:
- if [[ "$PHPLINT" == "1" ]]; then find -L .  -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l; fi
- if [[ "$PHPCS" == "1" ]]; then vendor/bin/phpcs -v; fi
