language: php

sudo: false

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: PHPLINT=1 PHPCS=1
    - php: 5.6
    - php: 7.1
      env: WP_VERSION=4.7
    - php: 5.5

cache:
  directories:
    - vendor

install:
- phpenv local 5.6
- composer selfupdate 1.0.0 --no-interaction
- composer install --no-interaction
- phpenv local --unset

script:
- if [[ "$PHPLINT" == "1" ]]; then find -L .  -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l; fi
- if [[ "$PHPCS" == "1" ]]; then vendor/bin/phpcs -v; fi
